import { appendFileSync, existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { randomUUID } from 'node:crypto'
import type { ApiClient } from '../api/client.js'
import type { Message } from '../api/types.js'
import { sessionsDir, sessionFile, sessionMetaFile } from './paths.js'
import { atomicWriteFile } from '../../utils/file/atomicWrite.js'
export interface SessionMeta { id: string; cwd: string; model: string; createdAt: number; updatedAt: number; messageCount: number; summary?: string }
function readMeta(dir: string, id: string): SessionMeta | null { try { return JSON.parse(readFileSync(sessionMetaFile(dir, id), 'utf8')) as SessionMeta } catch { return null } }
export function createSession(cwd: string, model: string): SessionMeta { const dir = sessionsDir(cwd); mkdirSync(dir, { recursive: true }); const now = Date.now(); const id = `${now.toString(36)}-${randomUUID().slice(0, 8)}`; const meta = { id, cwd, model, createdAt: now, updatedAt: now, messageCount: 0 }; writeFileSync(sessionMetaFile(dir, id), JSON.stringify(meta, null, 2) + '\n'); writeFileSync(sessionFile(dir, id), '', 'utf8'); return meta }
export function appendMessages(cwd: string, id: string, messages: Message[]): void { if (!messages.length) return; const dir = sessionsDir(cwd); appendFileSync(sessionFile(dir, id), messages.map(message => JSON.stringify(message)).join('\n') + '\n', 'utf8'); const meta = readMeta(dir, id); if (meta) { meta.updatedAt = Date.now(); meta.messageCount += messages.length; writeFileSync(sessionMetaFile(dir, id), JSON.stringify(meta, null, 2) + '\n') } }
export function replaceMessages(cwd: string, id: string, messages: Message[]): void { const dir = sessionsDir(cwd); mkdirSync(dir, { recursive: true }); const serialized = messages.map(message => JSON.stringify(message)).join('\n') + (messages.length ? '\n' : ''); atomicWriteFile(sessionFile(dir, id), serialized); const meta = readMeta(dir, id); if (meta) { meta.updatedAt = Date.now(); meta.messageCount = messages.length; atomicWriteFile(sessionMetaFile(dir, id), JSON.stringify(meta, null, 2) + '\n') } }
export function loadSession(cwd: string, id: string): { messages: Message[]; meta: SessionMeta | null } { const dir = sessionsDir(cwd); const messages: Message[] = []; try { for (const line of readFileSync(sessionFile(dir, id), 'utf8').split('\n')) { if (!line.trim()) continue; try { messages.push(JSON.parse(line) as Message) } catch { /* skip malformed */ } } } catch { /* missing session */ } return { messages, meta: readMeta(dir, id) } }
export function listSessions(cwd: string): SessionMeta[] { const dir = sessionsDir(cwd); if (!existsSync(dir)) return []; return readdirSync(dir).filter(name => name.endsWith('.meta.json')).map(name => readMeta(dir, name.slice(0, -10))).filter((meta): meta is SessionMeta => meta !== null).sort((a, b) => b.updatedAt - a.updatedAt) }
export async function summarizeSession(client: ApiClient, smallModel: string, messages: Message[]): Promise<string | undefined> { const text = messages.map(message => `[${message.role}] ${typeof message.content === 'string' ? message.content : JSON.stringify(message.content)}`).join('\n').slice(0, 50_000); try { const result = await client.callOnce({ model: smallModel, max_tokens: 256, system: 'Summarize this conversation in one concise sentence.', messages: [{ role: 'user', content: text }] }); return result.content.filter(block => block.type === 'text').map(block => block.text).join('').trim().slice(0, 200) || undefined } catch { return undefined } }
export function sessionMtime(dir: string, id: string): number { try { return statSync(sessionFile(dir, id)).mtimeMs } catch { return 0 } }
