import { spawn } from 'node:child_process'
import { readdirSync, readFileSync, statSync } from 'node:fs'
import { isAbsolute, join } from 'node:path'
import { buildTool, textToolResult } from '../../Tool.js'
function nodeGrep(pattern: string, root: string, mode: string, ignoreCase: boolean, lineNumbers: boolean): string[] { const out: string[] = []; const regex = new RegExp(pattern, ignoreCase ? 'i' : ''); function walk(dir: string) { for (const name of readdirSync(dir)) { if (['.git','node_modules','.svn','.hg'].includes(name)) continue; const path = join(dir, name); try { const stat = statSync(path); if (stat.isDirectory()) walk(path); else if (stat.size < 1_000_000) { const lines = readFileSync(path, 'utf8').split(/\r?\n/); const matches = lines.map((line, i) => regex.test(line) ? `${lineNumbers ? `${i + 1}:` : ''}${line}` : '').filter(Boolean); if (mode === 'files_with_matches' && matches.length) out.push(path); else if (mode === 'count' && matches.length) out.push(`${path}:${matches.length}`); else out.push(...matches.map(line => `${path}:${line}`)) } } catch { /* ignore unreadable */ } } } walk(root); return out }
function runRg(args: string[], cwd: string): Promise<{ code: number; stdout: string }> { return new Promise(resolve => { const child = spawn('rg', args, { cwd, stdio: ['ignore','pipe','ignore'] }); let stdout = ''; child.stdout.on('data', chunk => stdout += String(chunk)); child.on('error', () => resolve({ code: 2, stdout })); child.on('close', code => resolve({ code: code ?? 2, stdout })) }) }
export const GrepTool = buildTool<Record<string, unknown>, unknown>({ name: 'GrepTool', inputJSONSchema: { type: 'object', properties: { pattern: { type: 'string' }, path: { type: 'string' }, output_mode: { type: 'string' }, '-i': { type: 'boolean' }, '-n': { type: 'boolean' } }, required: ['pattern'] }, maxResultSizeChars: 30_000, isReadOnly: () => true, isConcurrencySafe: () => true,
  async call(input, context) { const pattern = String(input.pattern); const mode = String(input.output_mode ?? 'content'); const args = ['--hidden','--exclude-dir=.git','--exclude-dir=node_modules','--max-columns','500']; if (mode === 'files_with_matches') args.push('-l'); if (mode === 'count') args.push('-c'); if (input['-n'] !== false && mode === 'content') args.push('-n'); if (input['-i'] === true) args.push('-i'); if (pattern.startsWith('-')) args.push('-e'); args.push(pattern, String(input.path ?? '.')); const rg = await runRg(args, context.cwd); const fallbackPath = input.path ? (isAbsolute(String(input.path)) ? String(input.path) : join(context.cwd, String(input.path))) : context.cwd; const lines = rg.code <= 1 ? rg.stdout.trimEnd().split(/\r?\n/).filter(Boolean) : nodeGrep(pattern, fallbackPath, mode, input['-i'] === true, input['-n'] !== false); return { data: lines, result: lines.join('\n') } },
  description: input => `grep ${String(input.pattern ?? '')}`, prompt: () => 'Search files for a regular expression.', mapToolResultToToolResultBlockParam: textToolResult, renderToolUseMessage: input => String(input.pattern ?? '')
})
