import { spawn } from 'node:child_process'
import { buildTool, textToolResult, type ToolUseContext } from '../../Tool.js'
import { isReadOnlyCommand } from '../../utils/bash/ast.js'
export interface BashRunResult { stdout: string; stderr: string; exitCode: number | null; timedOut: boolean; backgrounded: false }
export function runBash(command: string, cwd: string, timeout = 120_000, signal?: AbortSignal): Promise<BashRunResult> { return new Promise(resolve => { const child = spawn(command, { shell: true, cwd, env: process.env, stdio: ['ignore','pipe','pipe'] }); let stdout = ''; let stderr = ''; let timedOut = false; const timer = setTimeout(() => { timedOut = true; child.kill('SIGTERM'); setTimeout(() => child.kill('SIGKILL'), 2000) }, timeout); const abort = () => child.kill('SIGTERM'); signal?.addEventListener('abort', abort, { once: true }); child.stdout.on('data', chunk => { if (stdout.length < 64 * 1024 * 1024) stdout += String(chunk).slice(0, 64 * 1024 * 1024 - stdout.length) }); child.stderr.on('data', chunk => { if (stderr.length < 64 * 1024 * 1024) stderr += String(chunk).slice(0, 64 * 1024 * 1024 - stderr.length) }); child.on('close', code => { clearTimeout(timer); signal?.removeEventListener('abort', abort); resolve({ stdout, stderr, exitCode: code, timedOut, backgrounded: false }) }) }) }
export const BashTool = buildTool<Record<string, unknown>, unknown>({ name: 'BashTool', inputJSONSchema: { type: 'object', properties: { command: { type: 'string' }, timeout: { type: 'integer' }, description: { type: 'string' }, run_in_background: { type: 'boolean' } }, required: ['command'] }, maxResultSizeChars: 30_000, isReadOnly: input => isReadOnlyCommand(String(input.command ?? '')),
  async call(input: Record<string, unknown>, context: ToolUseContext) { const result = await runBash(String(input.command ?? ''), context.cwd, Number(input.timeout ?? 120_000), context.abortController.signal); const text = result.stdout + (result.stderr ? `\n[stderr]\n${result.stderr}` : '') + (result.timedOut ? '\n[TIMEOUT]' : result.exitCode !== 0 ? `\n[exit code ${result.exitCode}]` : ''); return { data: result, result: text, isError: result.timedOut || result.exitCode !== 0 } },
  description: input => `run ${String(input.command ?? '').slice(0, 60)}`, prompt: () => 'Run a shell command in the project directory.', mapToolResultToToolResultBlockParam: textToolResult, renderToolUseMessage: input => String(input.command ?? '')
})
