import { existsSync, readFileSync, statSync } from 'node:fs'
import { canonicalPath } from '../../utils/file/canonicalPath.js'
import { isFullRead } from '../../utils/file/readFileState.js'
import { atomicWriteFile } from '../../utils/file/atomicWrite.js'
import { buildTool, textToolResult, type ToolUseContext } from '../../Tool.js'
export const NotebookEditTool = buildTool<Record<string, unknown>, unknown>({ name: 'NotebookEditTool', inputJSONSchema: { type: 'object', properties: { notebook_path: { type: 'string' }, cell_id: { type: 'string' }, cell_number: { type: 'integer', minimum: 0 }, new_source: { type: 'string' }, edit_mode: { type: 'string', enum: ['replace','insert','delete'] } }, required: ['notebook_path','new_source'] }, maxResultSizeChars: 10_000,
  async call(input, context: ToolUseContext) { const path = canonicalPath(String(input.notebook_path), context.cwd); if (!existsSync(path)) return { data: null, result: 'Notebook not found', isError: true }; const state = context.readFileState.get(path); if (!isFullRead(state)) return { data: null, result: 'Must read the notebook before editing', isError: true }; if (statSync(path).mtimeMs !== state?.mtimeMs) return { data: null, result: 'Notebook was modified since last read', isError: true }; let notebook: { cells: Array<{ id?: string; metadata?: { id?: string }; source: string | string[]; [key: string]: unknown }> }; try { notebook = JSON.parse(readFileSync(path, 'utf8')) as typeof notebook } catch (error) { return { data: null, result: `Invalid notebook: ${error instanceof Error ? error.message : String(error)}`, isError: true } }; const cells = notebook.cells; if (!Array.isArray(cells)) return { data: null, result: 'Invalid notebook: cells must be an array', isError: true }; let index = input.cell_id ? cells.findIndex(cell => cell.id === input.cell_id || cell.metadata?.id === input.cell_id) : Number(input.cell_number ?? 0); if (index < 0 || index >= cells.length) return { data: null, result: 'Cell not found', isError: true }; const mode = String(input.edit_mode ?? 'replace'); if (mode === 'delete') cells.splice(index, 1); else if (mode === 'insert') cells.splice(index, 0, { cell_type: 'code', metadata: {}, source: String(input.new_source).split('\n') }); else cells[index]!.source = String(input.new_source).split('\n'); atomicWriteFile(path, JSON.stringify(notebook, null, 1) + '\n'); context.readFileState.recordRead(path, statSync(path).mtimeMs); return { data: notebook, result: `Updated ${path}` } },
  description: input => `edit notebook ${String(input.notebook_path ?? '')}`, prompt: () => 'Edit a Jupyter notebook cell.', mapToolResultToToolResultBlockParam: textToolResult, renderToolUseMessage: input => String(input.notebook_path ?? '')
})
