import { existsSync, readFileSync, statSync } from 'node:fs'
import { buildTool, textToolResult, type ToolUseContext } from '../../Tool.js'
import { canonicalPath } from '../../utils/file/canonicalPath.js'
import { isFullRead } from '../../utils/file/readFileState.js'
import { atomicWriteFile } from '../../utils/file/atomicWrite.js'
function normalizeQuotes(value: string): string { return value.replace(/[‘’]/g, "'").replace(/[“”]/g, '"').replace(/–/g, '-').replace(/—/g, '--') }
function countOccurrences(haystack: string, needle: string): number { if (!needle) return 0; const source = normalizeQuotes(haystack); const target = normalizeQuotes(needle); let count = 0; let pos = 0; while ((pos = source.indexOf(target, pos)) >= 0) { count++; pos += target.length } return count }
export const FileEditTool = buildTool({ name: 'FileEditTool', inputJSONSchema: { type: 'object', properties: { file_path: { type: 'string' }, old_string: { type: 'string' }, new_string: { type: 'string' }, replace_all: { type: 'boolean' } }, required: ['file_path','old_string','new_string'] }, maxResultSizeChars: 10_000,
  async validateInput(input: Record<string, unknown>) { if (/^[\\/]{2}[^\\/]+[\\/]/.test(String(input.file_path ?? ''))) return { ok: false, message: 'UNC paths are not allowed' }; if (input.old_string === input.new_string) return { ok: false, message: 'old_string and new_string must differ' }; return { ok: true } },
  async call(input: Record<string, unknown>, context: ToolUseContext) { const path = canonicalPath(String(input.file_path), context.cwd); const oldString = String(input.old_string ?? ''); const newString = String(input.new_string ?? ''); if (!existsSync(path)) { if (oldString !== '') return { data: null, result: 'File not found; use old_string="" to create it', isError: true }; atomicWriteFile(path, newString); context.readFileState.recordRead(path, statSync(path).mtimeMs); return { data: newString, result: `Created ${path}` } } const state = context.readFileState.get(path); if (!isFullRead(state)) return { data: null, result: `Must read the file ${path} before editing`, isError: true }; const currentStat = statSync(path); if (currentStat.size > 1024 * 1024 * 1024) return { data: null, result: 'File is too large to edit safely', isError: true }; if (currentStat.mtimeMs !== state?.mtimeMs) return { data: null, result: 'File was modified since last read', isError: true }; const current = readFileSync(path, 'utf8'); const count = countOccurrences(current, oldString); if (!count) return { data: null, result: 'old_string not found', isError: true }; if (count > 1 && input.replace_all !== true) return { data: null, result: `old_string found ${count} times; set replace_all=true`, isError: true }; const normalized = normalizeQuotes(current); const needle = normalizeQuotes(oldString); const replacement = normalizeQuotes(newString); const output = input.replace_all === true ? normalized.split(needle).join(replacement) : normalized.replace(needle, replacement); atomicWriteFile(path, output); context.readFileState.recordRead(path, statSync(path).mtimeMs); return { data: output, result: `Updated ${path}` } },
  description: input => `edit ${String(input.file_path ?? '')}`, prompt: () => 'Edit a file with an exact string replacement. Read it first.', mapToolResultToToolResultBlockParam: textToolResult, renderToolUseMessage: input => String(input.file_path ?? '')
})
